### ISSUE TITLE
How can I use it in multiple modules' controllers

### ISSUE THREAD

**Issue by Menci** [chvarkov/google-recaptcha#10]
I imported it in `AppModule` but I can't use `@Recaptcha` in my other modules.

**Comment by Menci** [comment]
Now I export a `forRootAsync`-ed module object from `app.module.ts`:

```typescript
export const RecaptchaModule = GoogleRecaptchaModule.forRootAsync({
  imports: [ConfigModule],
  useFactory: (configService: ConfigService) => ({
    secretKey: configService.config.security.recaptchaSecret,
    response: (req: Request) => String(req.headers["x-recaptcha-token"]),
    skipIf: () => !configService.config.security.recaptchaSecret
  }),
  inject: [ConfigService],
});
```

Is there a better approach?

**Comment by chvarkov** [comment]
Hey @Menci, I understand your problem.

I think you need to use global module.

https://docs.nestjs.com/modules#global-modules

Example:

```
const MODULES = [
  GoogleRecaptchaModule.forRootAsync({
    imports: [ConfigModule],
    useFactory: (configService: ConfigService) => ({
      secretKey: configService.config.security.recaptchaSecret,
      response: (req: Request) => String(req.headers["x-recaptcha-token"]),
      skipIf: () => !configService.config.security.recaptchaSecret
    }),
    inject: [ConfigService],
  })
  Module2.forRoot(...),
  Module2.forRoot(...),
];

@Global()
@Module({
    imports: [...MODULES],
    exports: [...MODULES],
})
export class SharedModule {}
```


Import `SharedModule` to `AppModule`.

Then all providers will be available in all modules in your project without importing `SharedModule`.

I will add example in near future.

**Comment by chvarkov** [comment]
@Menci example with your case here https://github.com/chvarkov/google-recaptcha-example

**Comment by Menci** [comment]
Thanks. I refactored this approach. 🎉 https://github.com/syzoj/syzoj-ng/commit/3e49e334ed3f92d19eb0e9a3e58e11f7adeb42a9
