### ISSUE TITLE
Error: @nestlab/google-recaptcha tried to access rxjs

### ISSUE THREAD

**Issue by DiFuks** [chvarkov/google-recaptcha#100]
> Error: @nestlab/google-recaptcha tried to access rxjs, but it isn't declared in its dependencies; this makes the require call ambiguous and unsound.

The problem occurs when using yarn pnp mode, since rxjs is not listed in the peerDependencies list, but is used

**Comment by chvarkov** [comment]
Hi @DiFuks, thanks for your issue, declared as peerDependency since v3.1.8

**Comment by DiFuks** [comment]
Sorry I didn't say right away - same problem with axios dependency

**Comment by chvarkov** [comment]
@DiFuks v3.1.9
