### ISSUE TITLE
Update nestjs/axios to v1 and axios itself

### ISSUE THREAD

**Issue by Dzixxx** [chvarkov/google-recaptcha#103]
**Is your feature request related to a problem? Please describe.**
We have a new version of axios & nestjs/axios and we're blocked by this library with updating our project ;)

**Describe the solution you'd like**
Updating dependencies ;) 

**Describe alternatives you've considered**
There are no alternatives, I'd like to stay with yours package ;> 

**Additional context**
No extra context, it's just about updating deps (I'm not sure if this should be a major update)

**Comment by chvarkov** [comment]
Hi @Dzixxx, peer deps versions updated in v3.2.0

**Comment by Dzixxx** [comment]
Awesome! 😍 closing issue then, thank U! 🚀
