### ISSUE TITLE
Update NestJS to Support Version 10.0

### ISSUE THREAD

**Issue by ramirosacruz** [chvarkov/google-recaptcha#120]
I would like to request support for version 10.0 of NestJS in the GitHub repository. Currently, the repository is using an older version, and updating it to the latest release will ensure compatibility with the latest features and enhancements provided by NestJS.
![Screenshot_12](https://github.com/chvarkov/google-recaptcha/assets/40445502/8089770f-a327-4c29-b002-f1b8eacbb6c6)

NestJS version 10.0 brings significant improvements, bug fixes, and new functionalities that can greatly benefit our project. By upgrading to this version, we can take advantage of the latest optimizations and enhancements, ensuring a more robust and efficient application.

I kindly request the repository maintainers to review and incorporate the necessary changes to support NestJS 10.0. This may involve updating dependencies, making necessary code modifications, and ensuring overall compatibility with the new version.

Please let me know if there's any additional information or assistance required to proceed with this update. Thank you for your attention to this matter.

**Comment by chvarkov** [comment]
Hi @ramirosacruz, thanks for your issue. Added support NestJS 10 since v3.4.1

**Comment by ramirosacruz** [comment]
Thank you for the quick response. I appreciate your promptness in addressing my issue
