### ISSUE TITLE
Error when build nestjs app (@nestjs/core": "^8.2.2")

### ISSUE THREAD

**Issue by hienbase** [chvarkov/google-recaptcha#150]
![ảnh](https://github.com/user-attachments/assets/c1cccc82-0977-4ad2-bbe5-c0cdbbf143b5)

**Comment by chvarkov** [comment]
Hi @hienbase, thank you for reporting the issue.
The issue with nestjs 8 compatibility been fixed and published. Available since v3.8.0

**Comment by hienbase** [comment]
Thank you!
