### ISSUE TITLE
Nest can't resolve dependencies of the GoogleRecaptchaGuard

### ISSUE THREAD

**Issue by gcaggia** [chvarkov/google-recaptcha#18]
First of all, thank you for providing this awesome dependency!

I am having an issue with the  GoogleRecaptchaGuard or GoogleRecaptcha decorator.

Basically, I installed the package. Then I added it into my AppModule as followed: 

```typescript
@Module({
  imports: [
    GoogleRecaptchaModule.forRoot({
      secretKey: ConfigService.get('GOOGLE_RECAPTCHA_SECRET_KEY'),
      response: req => req.body.recaptcha,
      // skipIf: process.env.NODE_ENV !== 'production',
      useRecaptchaNet: false,
      agent: null,
    }),
    TypeOrmModule.forRoot(ConfigService.getTypeOrmConfig()),
    PingModule,
    ....
  ],
  providers: [ConfigService],
})
export class AppModule {}
```

Note: ConfigService.get is just a static method from my custom ConfigService class. Basically, it just returned a string from the .env file.

Then in a contact module, I imported the module:

```typescript
@Module({
  imports: [EmailingModule, GoogleRecaptchaModule],
  providers: [ContactService],
  controllers: [ContactController],
})
export class ContactModule {}
```

And in my Controller: 

```typescript
 @Recaptcha(req => req.body.recaptha)
  @Post('/message')
  @HttpCode(HttpStatus.ACCEPTED)
  async handleContactMessage(
    @Body(ValidationPipe) userContactPageDto: UserContactPageDto,
  ): Promise<ContactMessageResponseInterface> {
  //
}
```

Also `@UseGuards(GoogleRecaptchaGuard)` does not work too. 

I am having the following error:
 
```
Nest can't resolve dependencies of the GoogleRecaptchaGuard (?, Reflector, Symbol(RECAPTCHA_OPTIONS)). Please make sure that the argument GoogleRecaptchaValidator at index [0] is available in the ContactModule context.

Potential solutions:
- If GoogleRecaptchaValidator is a provider, is it part of the current ContactModule?
- If GoogleRecaptchaValidator is exported from a separate @Module, is that module imported within ContactModule?
  @Module({
    imports: [ /* the Module containing GoogleRecaptchaValidator */ ]
  })
 +1ms
Error: Nest can't resolve dependencies of the GoogleRecaptchaGuard (?, Reflector, Symbol(RECAPTCHA_OPTIONS)). Please make sure that the argument GoogleRecaptchaValidator at index [0] is available in the ContactModule context.

Potential solutions:
- If GoogleRecaptchaValidator is a provider, is it part of the current ContactModule?
- If GoogleRecaptchaValidator is exported from a separate @Module, is that module imported within ContactModule?
  @Module({
    imports: [ /* the Module containing GoogleRecaptchaValidator */ ]
  })
```

Did I miss something? 

Thank you.

**Comment by chvarkov** [comment]
Hey @gcaggia.
It's happening, because you import `GoogleRecaptchaModule` to `ContactModule` without calling `forRoot` or `forRootAsync` method.

In your case import `GoogleRecaptchaModule` to `AppModule` it probably doesn't make sense, since I don't see any declared controllers in it.

For solving your issue:
1. Change `ContactModule` like this:

```
@Module({
  imports: [
    EmailingModule,
    GoogleRecaptchaModule.forRoot({
      secretKey: ConfigService.get('GOOGLE_RECAPTCHA_SECRET_KEY'),
      response: req => req.body.recaptcha,
      // skipIf: process.env.NODE_ENV !== 'production',
      useRecaptchaNet: false,
      agent: null,
    }),
  ],
  providers: [ContactService],
  controllers: [ContactController],
})
export class ContactModule {}
```
2. Remove import `GoogleRecaptchaModule` from `AppModule` I seems doesn't make sense. Please check it.

If you need to use `GoogleRecaptchaModule` in many modules then I recommend use global modules.
https://docs.nestjs.com/modules#global-modules

You can see usage with global module here
https://github.com/chvarkov/google-recaptcha-example

**Comment by gcaggia** [comment]
@chvarkov Thank you for your reply.

Indeed it works fine now :-) 

I was a bit perfectionist and I wanted to do it like the TypeOrmModule or the SendGridModule where you import the module at the root of the application (AppModule) and then the configurations is done for all the app. 

Just out of curiosity, is there a way to do that with GoogleRecaptchaModule?

Otherwise, I just updated my application using your example and it works fine.

Thank you.

**Comment by chvarkov** [comment]
@gcaggia I think it's good idea and I will implement it soon. Thanks.

**Comment by gcaggia** [comment]
@chvarkov Awsome! If you need any help or If I can contribute to any feature, let me know!

**Comment by chvarkov** [comment]
@gcaggia Thank you for the offer of help, I will keep in mind)
