### ISSUE TITLE
Extend peer dependencies

### ISSUE THREAD

**Issue by alvaro-octal** [chvarkov/google-recaptcha#21]
Hi,

First of all, thanks for your work, it really saved me a lot of time. I've been using this library with NestJS 7 and it works fine, could you extend the peer dependencies?

```
[...]
"@nestjs/core": ">=6.0.0 <8.0.0",
"@nestjs/common": ">=6.0.0 <8.0.0",
[...]
```

**Comment by chvarkov** [comment]
Hi @alvaro-octal. Thanks for your feedback. Peer dependencies was extended. This changes available since 1.1.10 version.
