### ISSUE TITLE
Exception text should be more precise and in array

### ISSUE THREAD

**Issue by nikitauskas** [chvarkov/google-recaptcha#31]
Right now if captcha is not valid I receive an error message "The response parameter is missing."
I show an error message on my form, and it's hard for a user to understand which parameter is missing.
can we set an error message as a parameter or at least change the text to "The Captcha is not valid"

Nest js throws errors in array object even it's only one error:
for example:
{"statusCode":400,"message":["Passwords must be a minimum of 8 characters, include upper and lowercase letters and at least one number"],"error":"Bad Request"}

however, google-recaptcha throws an error as a string:
{"statusCode":400,"message":"The response parameter is missing."}

it's an additional step on the client to handle such difference, please fix it.

overall your project works fine and I love it.

thanks!

**Expected behavior**
expect an error in array and text should be more clear

**Comment by nikitauskas** [comment]
I'm new with nest.js but seems it's not always an array of issues..

**Comment by chvarkov** [comment]
Hi @nikitauskas 

Only you decide which error response format you want to use.

You can create exception filter for handle google recapthca exceptions and transform to format that you want.

I see you want to use an default format from validation pipe exception. Okay, you need to do:

1. Create new exception filter


```
@Catch(GoogleRecaptchaException)
export class GoogleRecaptchaFilter implements ExceptionFilter {
    catch(exception: GoogleRecaptchaException, host: ArgumentsHost): any {
        const res: Response = host.switchToHttp().getResponse();
        res.status(exception.getStatus()).send({
            statusCode: exception.getStatus(),
            message: this.transformCodesToMessages(exception.errorCodes),
            error: exception.getStatus() === HttpStatus.BAD_REQUEST ? 'Bad request' : 'Internal server error',
        });
    }

    transformCodesToMessages(errorCodes: ErrorCode[]): string[] {
        // TODO: Change messages
        return errorCodes.map(errorCode => {
            switch (errorCode) {
                case ErrorCode.InvalidInputResponse:
                    return 'The response parameter is invalid or malformed.';

                case ErrorCode.MissingInputResponse:
                    return 'The response parameter is missing.';
                case ErrorCode.TimeoutOrDuplicate:
                    return 'The response is no longer valid: either is too old or has been used previously.';

                case ErrorCode.InvalidInputSecret:
                case ErrorCode.MissingInputSecret:
                    return 'Invalid module configuration. Please check public-secret keys.';

                case ErrorCode.UnknownError:
                case ErrorCode.BadRequest:
                default:
                    return 'Unexpected error.';
            }
        })
    }
}

```

2. Add GoogleRecaptchaFilter to application as global filter

main.ts
```
async function bootstrap() {
    const app = await NestFactory.create(AppModule);
    app.useGlobalFilters(new ErrorFilter(), new GoogleRecaptchaFilter());
    await app.listen(3000);
}
bootstrap();
```

**! Add your google recaptcha filter after main filter**

You can see usage example with exception filter [here](https://github.com/chvarkov/google-recaptcha-example)
More about global exception filter you can read [here](https://docs.nestjs.com/exception-filters#catch-everything)

**Comment by nikitauskas** [comment]
thanks, man
