### ISSUE TITLE
Allow score validation for ReCAPTCHA v3 compatibility

### ISSUE THREAD

**Issue by katebrune** [chvarkov/google-recaptcha#37]
**Is your feature request related to a problem? Please describe.**
Currently using this module with ReCAPTCHA v2, but was looking into upgrading to v3. The site verify response for v3 contains a score to use to take variable action

![image](https://user-images.githubusercontent.com/31379789/113182446-8600c580-9218-11eb-9997-5e14944dd19b.png)

Currently the validator used in this module only takes 'success' into consideration

**Describe the solution you'd like**
I would like the `GoogleRecaptchaValidatorOptions` extended to include `score`. During validation, if the returned score >= the given score threshold, return success, else throw exception

**Describe alternatives you've considered**
Another option would be to have the `GoogleRecaptchaValidator` be a custom provider & allow injecting a custom validator into the module

**Comment by chvarkov** [comment]
Hi @katebrune , It's great feature request. I'll do it as soon as possible.

**Comment by chvarkov** [comment]
Hi @katebrune, the feature was implemented and published. Available since version 2.0.0.

**Comment by bmitchinson** [comment]
Thanks @chvarkov
