### ISSUE TITLE
Error 400 - The response parameter is invalid or malformed

### ISSUE THREAD

**Issue by felinto-dev** [chvarkov/google-recaptcha#40]
Helo!

When trying to configure an endpoint to use captcha I get this error:

```json
{
  "statusCode": 400,
  "message": "The response parameter is invalid or malformed."
}
```

Is there anything I'm losing sight of? According to the documentation this error is triggered by Google Recaptcha and is not related to the plugin, however, when researching this problem regarding nestjslab I did not find any post. I hope this can help other people who have the same question.

app.module.ts
```ts
    GoogleRecaptchaModule.forRoot({
      secretKey: 'MY SECRET KEY',
      response: (req) => req.headers.recaptcha,
      network: GoogleRecaptchaNetwork.Recaptcha,
      agent: null,
    }),
```

endpoint.controller.ts
```ts
  @Recaptcha()
  @Get()
  async getEndpoint(
```

I did nothing more than that.

Another question. Can I use recaptcha in the local development environment? (localhost)
I tried and it didn't work, I think it makes sense because the recaptcha service will not be able to authenticate itself.

I used [ngrok](https://ngrok.com/) for testing purposes, and the result was the same.

**Comment by chvarkov** [comment]
Hi @felinto-dev.
It looks like you don't provide header "recaptcha" from client side. The header must be contains google recaptcha token.
You can check usage example here: [google-recaptcha-example](https://github.com/chvarkov/google-recaptcha-example)

Exactly you can use localhost. But make sure that allowed domains contains localhost in google recaptcha admin console.
![image](https://user-images.githubusercontent.com/42495856/113505616-af875d00-9548-11eb-8e58-7849c35c30d4.png)

**Comment by chvarkov** [comment]
@felinto-dev  Let me know if issue was resolved for you.

**Comment by felinto-dev** [comment]
Thanks for your quick response and I'm sorry for the delay, I couldn't reply in time.

In the first answer, in the app.module.ts you can see that the google recaptcha header is already provided. I took this example from the documentation. Can I be missing something?

**Comment by chvarkov** [comment]
@felinto-dev  Check please recaptcha header in your request

![image](https://user-images.githubusercontent.com/42495856/113748842-a1d10380-9711-11eb-9ab4-3a05c4d75db6.png)

I seems it can be empty in your case.

Example on client side.
```
        const recaptcha = grecaptcha.getResponse();
        grecaptcha.reset();

        const res = await http.post('http://localhost:3000/api/endpoint', {}, {
            recaptcha,
        });
```
