### ISSUE TITLE
Unexpected error. Please submit issue to @nestlab/google-recaptcha.

### ISSUE THREAD

**Issue by 901F** [chvarkov/google-recaptcha#59]
**Describe the bug**
I use Recaptcha V3 implement with Angular 13
I found error "Unexpected error. Please submit issue to @nestlab/google-recaptcha."
on some user in my web application

**To Reproduce**
I can't reproduce this because user said wait about 5 minute it will fine.

**Expected behavior**
I think because user agent I found usually issue happen on Android

**Screenshots**
![image](https://user-images.githubusercontent.com/9088059/162621737-5ed957ef-54a9-4a4d-8fb0-d39ed8b80341.png)

**Additional context**
List of User Agent has found this problem
- Mozilla/5.0 (Linux; Android 11; vivo 1904) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.79 Mobile Safari/537.36
- Mozilla/5.0 (Linux; Android 10; vivo 1935) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.79 Mobile Safari/537.36
- Mozilla/5.0 (Linux; Android 11; Redmi Note 8) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/94.0.4606.85 Mobile Safari/537.36
- Mozilla/5.0 (Linux; Android 11; vivo 1901) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.79 Mobile Safari/537.36

**Comment by chvarkov** [comment]
@MADCAZ Hi, which version do you use?

**Comment by MADCAZ** [comment]
> @MADCAZ Hi, which version do you use?

@nestlab/google-recaptcha: 2.1.2

**Comment by chvarkov** [comment]
@MADCAZ Hi could you update the package to latest version and add module option `debug: true`. I just need more information about your error.

**Comment by hoangkm-vnext** [comment]
I have same error.
@nestlab/google-recaptcha: 3.2.0
@nestjs/core: 8.0.0
![test](https://user-images.githubusercontent.com/91523143/205198426-acf24236-b46a-485c-9701-18078df8810b.png)

**Comment by chvarkov** [comment]
Hi @hoangkm-vnext , which recaptcha version are you using? v2 or v3?

**Comment by hoangkm-vnext** [comment]
> Hi @hoangkm-vnext , which recaptcha version are you using? v2 or v3?

v2

**Comment by chvarkov** [comment]
@hoangkm-vnext  I couldn't reproduce it. Do you have a chance to log response in utf-8 encodding?
I need to know which json response you received from recaptcha server.
