### ISSUE TITLE
Logging captcha result

### ISSUE THREAD

**Issue by smsalisbury** [chvarkov/google-recaptcha#60]
**Is your feature request related to a problem? Please describe.**
I'd like to be able to log the recaptcha result, regardless of whether it fails or succeeds.

**Describe the solution you'd like**
I'd like something in the module config that will let me capture the recaptcha result and log it.

**Describe alternatives you've considered**
I've tried using `axiosConfig`, but it looks like all options where this would be possible have been stripped out.

I've tried getting the result in the controller using the decorator, but that won't give me insight into failed results.

**Comment by chvarkov** [comment]
Hi @smsalisbury
Now logging available since v3.0.2
For use it set option `debug: true`, also you can use custom logger that extended from `Logger` (from `@nestjs/common`) set option `logger?: Logger`

**Comment by smsalisbury** [comment]
Looks great! Our project isn't ready to upgrade to NestJS 9 yet, but I checked it out on a test project and that seems to be what I'm looking for.
