### ISSUE TITLE
Unknown type in useFactory

### ISSUE THREAD

**Issue by DiFuks** [chvarkov/google-recaptcha#99]
The arguments to useFactory must be of type any[]

<img width="983" alt="image" src="https://user-images.githubusercontent.com/12777199/191468521-0cafd8e7-fded-404e-800c-adf33d028ba6.png">

**Comment by DiFuks** [comment]
This error occurs when the strictNullChecks option is enabled. When disabled:

<img width="1083" alt="image" src="https://user-images.githubusercontent.com/12777199/191469481-1344d8b4-ec9b-4627-a6c5-128b09ac817b.png">

**Comment by chvarkov** [comment]
Hi @DiFuks, thanks for your issue, fixed, available since v3.1.8
